changelog:
  categories:
  - title: Helix
    labels:
    - helix
  - title: Ghostty
    labels:
    - ghostty
  - title: Alacritty
    labels:
    - alacritty
  - title: Neovim
    labels:
    - nvim
  - title: VS Code
    labels:
    - vscode
  - title: Starship
    labels:
    - starship
  - title: tmux
    labels:
    - tmux
  - title: Zellij
    labels:
    - zellij
  - title: Lazygit
    labels:
    - lazygit
  - title: gh-dash
    labels:
    - gh-dash
  - title: macOS Terminal
    labels:
    - terminal
  - title: zsh
    labels:
    - zsh
  - title: fzf
    labels:
    - fzf
  - title: bat
    labels:
    - bat
  - title: delta
    labels:
    - delta
  - title: Chrome
    labels:
    - chrome
  - title: Slack
    labels:
    - slack
  - title: 🎨 Palette
    labels:
    - palette
  - title: 🏮 Core / Generator
    labels:
    - core
    - generator
  - title: Other Changes
    labels:
    - "*"
